default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5

development:
  <<: *default
  host: localhost
  database: 'swiggy_test_development'
  username: 'root'
  password: 'root'
